# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-17 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('gj', '高级'), ('zj', '中级'), ('cj', '低级')], max_length=2, verbose_name='难度'),
        ),
    ]
