# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-07 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowLevelCourse',
            fields=[
            ],
            options={
                'verbose_name': '低级课程',
                'verbose_name_plural': '低级课程',
                'proxy': True,
            },
            bases=('courses.course',),
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
    ]
