# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-12 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='T1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('nickname', models.CharField(max_length=10, null=True)),
                ('height', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('weight', models.CharField(blank=True, max_length=10, unique=True)),
                ('t1', models.CharField(max_length=10)),
                ('t2', models.CharField(max_length=10)),
            ],
        ),
    ]
