# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-02 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180517_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='image/2018/05/default_middile_2.png', upload_to='image/%Y/%m'),
        ),
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together=set([('email',)]),
        ),
    ]
